require 'rubygems'
require 'rake'
require 'spec/rake/spectask'

desc "Run all examples"
Spec::Rake::SpecTask.new('examples') do |t|
  t.rcov          = false
  t.pattern       = 'examples/**/*_spec.rb'
  t.spec_opts     = [ "--format", "html:reports/rspec.html", "--diff" ]
  t.fail_on_error = false
end


